/*
 * Copyright (C) 2025 Texas Instruments Incorporated - https://www.ti.com
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef TRACE_PROTOCOL_H
#define TRACE_PROTOCOL_H

/** PM debug actions */
#define TRACE_PM_ACTION_DEVICE_ON			 0x0U
#define TRACE_PM_ACTION_DEVICE_OFF			 0x1U
#define TRACE_PM_ACTION_CLOCK_ENABLE			 0x2U
#define TRACE_PM_ACTION_CLOCK_DISABLE			 0x3U
#define TRACE_PM_ACTION_CLOCK_SET_RATE			 0x4U
#define TRACE_PM_ACTION_CLOCK_SET_PARENT		 0x5U
#define TRACE_PM_ACTION_MSG_RECEIVED			 0x6U
#define TRACE_PM_ACTION_MSG_PARAM_DEV_CLK_ID		 0x7U
#define TRACE_PM_ACTION_MSG_PARAM_VAL			 0x8U
#define TRACE_PM_ACTION_WAKE_ARM			 0x9U
#define TRACE_PM_ACTION_WAKE_HANDLER			 0xAU
#define TRACE_PM_ACTION_PD_GET				 0xBU
#define TRACE_PM_ACTION_PD_PUT				 0xCU
#define TRACE_PM_ACTION_SET_LOCAL_RESET			 0xDU
#define TRACE_PM_ACTION_MODULE_GET			 0xEU
#define TRACE_PM_ACTION_MODULE_PUT			 0xFU
#define TRACE_PM_ACTION_RETENTION_GET			 0x10U
#define TRACE_PM_ACTION_RETENTION_PUT			 0x11U
#define TRACE_PM_ACTION_PD_INIT				 0x12U
#define TRACE_PM_ACTION_INVALID_PSC_DATA		 0x13U
#define TRACE_PM_ACTION_PSC_TRANSITION_TIMEOUT		 0x14U
#define TRACE_PM_ACTION_PSC_INVALID_DEP_DATA		 0x15U
#define TRACE_PM_ACTION_PSC_RST_DONE_TIMEOUT		 0x16U
#define TRACE_PM_ACTION_SET_MODULE_RESET		 0x17U
#define TRACE_PM_ACTION_INIT				 0x20U
#define TRACE_PM_ACTION_DEV_INIT			 0x21U
#define TRACE_PM_ACTION_SYSRESET			 0x22U
#define TRACE_PM_ACTION_LPM_SEQUENCE			 0x30U
#define TRACE_PM_ACTION_FAIL				 0x40U
#define TRACE_PM_ACTION_EXCLUSIVE_BUSY			 0x7BU
#define TRACE_PM_ACTION_EXCLUSIVE_DEVICE		 0x7CU
#define TRACE_PM_ACTION_INVALID_STATE			 0x7DU
#define TRACE_PM_ACTION_BAD_DEVICE			 0x7EU
#define TRACE_PM_ACTION_MSG_PARAM_LATENCY		 0x18U

#define TRACE_PM_VAL_CLOCK_VAL_SHIFT			 10U
#define TRACE_PM_VAL_CLOCK_VAL_MASK			 0x0001FC00U
#define TRACE_PM_VAL_CLOCK_EXP_SHIFT			 17U
#define TRACE_PM_VAL_CLOCK_EXP_MASK			 0x003E0000U
#define TRACE_PM_VAL_CLOCK_ID_SHIFT			 0U
#define TRACE_PM_VAL_CLOCK_ID_MASK			 0x000003FFU
#define TRACE_PM_VAL_MAX_FREQ				 (TRACE_PM_VAL_CLOCK_VAL_MASK >> \
							  TRACE_PM_VAL_CLOCK_VAL_SHIFT)

#define TRACE_PM_VAL_PSC_SHIFT				 20U
#define TRACE_PM_VAL_PD_SHIFT				 13U
#define TRACE_PM_VAL_LPSC_SHIFT				 13U

#define TRACE_PM_VAL_MAX_PSC_DATA			 0x00001FFFU

#define TRACE_PM_VAL_PD_POS1				 1U
#define TRACE_PM_VAL_PD_POS2				 2U
#define TRACE_PM_VAL_PD_POS3				 3U
#define TRACE_PM_VAL_PD_POS4				 4U
#define TRACE_PM_VAL_PD_POS5				 5U
#define TRACE_PM_VAL_PD_POS6				 6U
#define TRACE_PM_VAL_PD_POS7				 7U

#define TRACE_PM_MSG_CLK_ID_SHIFT			 10U

#define TRACE_PM_VAL_INIT_ERR_MASK			 0xFFFFU
#define TRACE_PM_VAL_INIT_ERR_SHIFT			 0U
#define TRACE_PM_VAL_INIT_IDX_MASK			 0x7U
#define TRACE_PM_VAL_INIT_IDX_SHIFT			 16U
#define TRACE_PM_VAL_INIT_DEFER				 (0x1U << 19)
#define TRACE_PM_VAL_INIT_ERROR				 (0x1U << 20)

#define TRACE_PM_VAL_DEV_INIT_ERR_MASK			 0x0FFFU
#define TRACE_PM_VAL_DEV_INIT_ERR_SHIFT			 0U
#define TRACE_PM_VAL_DEV_INIT_DEVICE_ID_SHIFT		 12U
#define TRACE_PM_VAL_DEV_INIT_DEVICE_ID_MASK		 0x3FFU

#define TRACE_PM_ACTION_SYSRESET_DOMAIN_MASK		 0x3FC000U
#define TRACE_PM_ACTION_SYSRESET_DOMAIN_SHIFT		 14U
#define TRACE_PM_ACTION_SYSRESET_ERR_MASK		 0x3FFFU
#define TRACE_PM_ACTION_SYSRESET_ERR_SHIFT		 0U
#define TRACE_PM_ACTION_SYSRESET_ERR_VAL_SUCCESS	 0x0U
#define TRACE_PM_ACTION_SYSRESET_ERR_VAL_INVALID_ARG	 0x1U
#define TRACE_PM_ACTION_SYSRESET_ERR_VAL_WRITE_FAIL	 0x2U
#define TRACE_PM_ACTION_SYSRESET_ERR_VAL_TIMEOUT	 0x3U
#define TRACE_PM_ACTION_SYSRESET_ERR_VAL_DEINIT_FAIL	 0x4U

#define TRACE_PM_VAL_EXCLUSIVE_BUSY_DEVICE_ID_SHIFT	 12U
#define TRACE_PM_VAL_EXCLUSIVE_BUSY_DEVICE_ID_MASK	 0x003FF000U
#define TRACE_PM_VAL_EXCLUSIVE_BUSY_RHOST_ID_SHIFT	 6U
#define TRACE_PM_VAL_EXCLUSIVE_BUSY_RHOST_ID_MASK	 0x00000FC0U
#define TRACE_PM_VAL_EXCLUSIVE_BUSY_EHOST_ID_SHIFT	 0U
#define TRACE_PM_VAL_EXCLUSIVE_BUSY_EHOST_ID_MASK	 0x0000003FU

#define TRACE_PM_VAL_EXCLUSIVE_DEVICE_ID_SHIFT		 8U
#define TRACE_PM_VAL_EXCLUSIVE_DEVICE_ID_MASK		 0x003FFF00U
#define TRACE_PM_VAL_EXCLUSIVE_HOST_ID_SHIFT		 0UL
#define TRACE_PM_VAL_EXCLUSIVE_HOST_ID_MASK		 0x000000FFU

#endif
