/*
 * Copyright (C) 2026 Texas Instruments Incorporated - https://www.ti.com/
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef SCMI_PD_DATA_H
#define SCMI_PD_DATA_H

#include <stdint.h>

#include <ti_devices.h>

#define xstr(s) str(s)
#define str(s) #s

struct ti_power_domain {
	char *name;
	uint32_t id;
};

#define AM62L_POWER_DOMAIN(_dev_id, _name)	\
{						\
	.id	= AM62LX_DEV_ ## _dev_id,	\
	.name	= _name,			\
}

static struct ti_power_domain scmi_power_domains[] = {
	AM62L_POWER_DOMAIN(ADC0, str(ADC0)),
	AM62L_POWER_DOMAIN(MAIN_GPIOMUX_INTROUTER0, str(M_GPIOMX_INTR0)),
	AM62L_POWER_DOMAIN(TIMESYNC_INTROUTER0, str(TIMESYNC_INTR0)),
	AM62L_POWER_DOMAIN(CPSW0, str(CPSW0)),
	AM62L_POWER_DOMAIN(CPT2_AGGR0, str(CPT2_AGGR0)),
	AM62L_POWER_DOMAIN(CPT2_AGGR1, str(CPT2_AGGR1)),
	AM62L_POWER_DOMAIN(WKUP_CPT2_AGGR0, str(WK_CPT2_AGGR0)),
	AM62L_POWER_DOMAIN(STM0, str(STM0)),
	AM62L_POWER_DOMAIN(DEBUGSS_WRAP0, str(DEBUGSS_WRAP0)),
	AM62L_POWER_DOMAIN(DMASS0, str(DMASS0)),
	AM62L_POWER_DOMAIN(DMASS0_BCDMA_0, str(DMASS0_BCDMA)),
	AM62L_POWER_DOMAIN(DMASS0_PKTDMA_0, str(DMASS0_PKTDM)),
	AM62L_POWER_DOMAIN(WKUP_DMASS0, str(WKUP_DMA0)),
	AM62L_POWER_DOMAIN(WKUP_DMASS0_DTHE, str(WK_DMA0_DTHE)),
	AM62L_POWER_DOMAIN(WKUP_DMASS0_XLCDMA_0, str(WK_DMA_XLCDMA)),
	AM62L_POWER_DOMAIN(TIMER0, str(TIMER0)),
	AM62L_POWER_DOMAIN(TIMER1, str(TIMER1)),
	AM62L_POWER_DOMAIN(TIMER2, str(TIMER2)),
	AM62L_POWER_DOMAIN(TIMER3, str(TIMER3)),
	AM62L_POWER_DOMAIN(WKUP_TIMER0, str(WKUP_TIMER0)),
	AM62L_POWER_DOMAIN(WKUP_TIMER1, str(WKUP_TIMER1)),
	AM62L_POWER_DOMAIN(WKUP_SMS_LITE0, str(WKUP_SMS_LITE0)),
	AM62L_POWER_DOMAIN(ECAP0, str(ECAP0)),
	AM62L_POWER_DOMAIN(ECAP1, str(ECAP1)),
	AM62L_POWER_DOMAIN(ECAP2, str(ECAP2)),
	AM62L_POWER_DOMAIN(ELM0, str(ELM0)),
	AM62L_POWER_DOMAIN(MMCSD1, str(MMCSD1)),
	AM62L_POWER_DOMAIN(MMCSD2, str(MMCSD2)),
	AM62L_POWER_DOMAIN(MMCSD0, str(MMCSD0)),
	AM62L_POWER_DOMAIN(EQEP0, str(EQEP0)),
	AM62L_POWER_DOMAIN(EQEP1, str(EQEP1)),
	AM62L_POWER_DOMAIN(EQEP2, str(EQEP2)),
	AM62L_POWER_DOMAIN(FSS0, str(FSS0)),
	AM62L_POWER_DOMAIN(GICSS0, str(GICSS0)),
	AM62L_POWER_DOMAIN(GPIO0, str(GPIO0)),
	AM62L_POWER_DOMAIN(GPIO2, str(GPIO2)),
	AM62L_POWER_DOMAIN(WKUP_GPIO0, str(WKUP_GPIO0)),
	AM62L_POWER_DOMAIN(GPMC0, str(GPMC0)),
	AM62L_POWER_DOMAIN(DSS_DSI0, str(DSS_DSI0)),
	AM62L_POWER_DOMAIN(DSS0, str(DSS0)),
	AM62L_POWER_DOMAIN(EPWM0, str(EPWM0)),
	AM62L_POWER_DOMAIN(EPWM1, str(EPWM1)),
	AM62L_POWER_DOMAIN(EPWM2, str(EPWM2)),
	AM62L_POWER_DOMAIN(LED0, str(LED0)),
	AM62L_POWER_DOMAIN(PBIST0, str(PBIST0)),
	AM62L_POWER_DOMAIN(WKUP_PBIST0, str(WKUP_PBIST0)),
	AM62L_POWER_DOMAIN(WKUP_VTM0, str(WKUP_VTM0)),
	AM62L_POWER_DOMAIN(MCAN0, str(MCAN0)),
	AM62L_POWER_DOMAIN(MCAN1, str(MCAN1)),
	AM62L_POWER_DOMAIN(MCAN2, str(MCAN2)),
	AM62L_POWER_DOMAIN(MCASP0, str(MCASP0)),
	AM62L_POWER_DOMAIN(MCASP1, str(MCASP1)),
	AM62L_POWER_DOMAIN(MCASP2, str(MCASP2)),
	AM62L_POWER_DOMAIN(I2C0, str(I2C0)),
	AM62L_POWER_DOMAIN(I2C1, str(I2C1)),
	AM62L_POWER_DOMAIN(I2C2, str(I2C2)),
	AM62L_POWER_DOMAIN(I2C3, str(I2C3)),
	AM62L_POWER_DOMAIN(WKUP_I2C0, str(WKUP_I2C0)),
	AM62L_POWER_DOMAIN(WKUP_GTC0, str(WKUP_GTC0)),
	AM62L_POWER_DOMAIN(WKUP_RTCSS0, str(WKUP_RTCSS0)),
	AM62L_POWER_DOMAIN(RTI0, str(RTI0)),
	AM62L_POWER_DOMAIN(RTI1, str(RTI1)),
	AM62L_POWER_DOMAIN(DEBUGSS0, str(DEBUGSS0)),
	AM62L_POWER_DOMAIN(MSRAM_96K0, str(MSRAM_96K0)),
	AM62L_POWER_DOMAIN(WKUP_PSRAM_64K0, str(WK_PSRAM_64K0)),
	AM62L_POWER_DOMAIN(ROM0, str(ROM0)),
	AM62L_POWER_DOMAIN(PSC0, str(PSC0)),
	AM62L_POWER_DOMAIN(WKUP_DEEPSLEEP_SOURCES0, str(WK_DPSLP_SR0)),
	AM62L_POWER_DOMAIN(MCU_MCU_16FF0, str(MCU_MCU_16FF0)),
	AM62L_POWER_DOMAIN(COMPUTE_CLUSTER0_ARM_COREPACK_0, str(ARM_COREPACK_0)),
	AM62L_POWER_DOMAIN(DDR16SS0, str(DDR16SS0)),
	AM62L_POWER_DOMAIN(WKUP_DFTSS0, str(WKUP_DFTSS0)),
	AM62L_POWER_DOMAIN(MCSPI0, str(MCSPI0)),
	AM62L_POWER_DOMAIN(MCSPI1, str(MCSPI1)),
	AM62L_POWER_DOMAIN(MCSPI2, str(MCSPI2)),
	AM62L_POWER_DOMAIN(MCSPI3, str(MCSPI3)),
	AM62L_POWER_DOMAIN(TRNG_DRBG_EIP76D_WRAP0, str(TRNG_EIP76_WP)),
	AM62L_POWER_DOMAIN(UART1, str(UART1)),
	AM62L_POWER_DOMAIN(UART2, str(UART2)),
	AM62L_POWER_DOMAIN(UART3, str(UART3)),
	AM62L_POWER_DOMAIN(UART4, str(UART4)),
	AM62L_POWER_DOMAIN(UART5, str(UART5)),
	AM62L_POWER_DOMAIN(UART6, str(UART6)),
	AM62L_POWER_DOMAIN(WKUP_UART0, str(WKUP_UART0)),
	AM62L_POWER_DOMAIN(USB0, str(USB0)),
	AM62L_POWER_DOMAIN(USB1, str(USB1)),
	AM62L_POWER_DOMAIN(DPHY_TX0, str(DPHY_TX0)),
	AM62L_POWER_DOMAIN(COMPUTE_CLUSTER0_CLKDIV_0, str(CLKDIV_0)),
	AM62L_POWER_DOMAIN(COMPUTE_CLUSTER0_PBIST_0, str(PBIST_0)),
	AM62L_POWER_DOMAIN(UART0, str(UART0)),
	AM62L_POWER_DOMAIN(BOARD0, str(BOARD0)),
	AM62L_POWER_DOMAIN(WKUP_GTCCLK_SEL_DEV_VD, str(WK_GTCCLK_VD)),
	AM62L_POWER_DOMAIN(WKUP_OBSCLK_MUX_SEL_DEV_VD, str(WK_OBSCLK_MUX)),
	AM62L_POWER_DOMAIN(WKUP_CLKOUT_SEL_DEV_VD, str(WK_CLKOUT_VD)),
	AM62L_POWER_DOMAIN(OBSCLK0_MUX_SEL_DEV_VD, str(OBSCLK0_MUX)),
	AM62L_POWER_DOMAIN(MAIN_USB0_ISO_VD, str(USB0_ISO_VD)),
	AM62L_POWER_DOMAIN(MAIN_USB1_ISO_VD, str(USB1_ISO_VD)),
	AM62L_POWER_DOMAIN(CLK_32K_RC_SEL_DEV_VD, str(CLK_32K_RC)),
	AM62L_POWER_DOMAIN(COMPUTE_CLUSTER0_A53_0, str(A53_0)),
	AM62L_POWER_DOMAIN(COMPUTE_CLUSTER0_A53_1, str(A53_1)),
	AM62L_POWER_DOMAIN(TIMER1_CLKSEL_VD, str(TIMER1_VD)),
	AM62L_POWER_DOMAIN(TIMER3_CLKSEL_VD, str(TIMER3_VD)),
	AM62L_POWER_DOMAIN(WKUP_TIMER1_CLKSEL_VD, str(WKUP_TIMER_VD)),
};

#endif /* SCMI_PD_DATA_H */
